# Generated by Django 5.2.6 on 2025-09-12 16:16

from django.db import migrations


def add_drinks_data(apps, schema_editor):
    Drinks = apps.get_model('myapp', 'Drinks')
    
    drinks_data = [
        {'drink_name': 'Coffee', 'price': 3},
        {'drink_name': 'Tea', 'price': 2},
        {'drink_name': 'Cappuccino', 'price': 4},
        {'drink_name': 'Latte', 'price': 5},
        {'drink_name': 'Espresso', 'price': 2},
        {'drink_name': 'Hot Chocolate', 'price': 3},
        {'drink_name': 'Green Tea', 'price': 2},
        {'drink_name': 'Americano', 'price': 3},
    ]
    
    for drink in drinks_data:
        Drinks.objects.create(**drink)


def remove_drinks_data(apps, schema_editor):
    Drinks = apps.get_model('myapp', 'Drinks')
    Drinks.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_drinks_data, remove_drinks_data),
    ]
